stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - data/raw/iris.csv
      - params.yaml
    params:
      - prepare.test_size
      - prepare.random_state
      - prepare.target_column
    outs:
      - data/prepared/train.csv
      - data/prepared/test.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/prepared/train.csv
      - data/prepared/test.csv
      - params.yaml
    params:
      - train.model_type
      - train.random_state
      - train.n_estimators
    outs:
      - data/models/model.pkl
    metrics:
      - metrics.json:
          cache: false